services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: task-tracker:${BUILD_NUMBER:-local}

    ports:
      - "3000:3000"

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
